In [1]:
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
from sklearn.neighbors import KNeighborsRegressor

In [2]:
df = pd.read_csv("./test/set_03_data.csv")
df.head()

,screen_size,ROM,RAM,n_rear_cam,n_front_cam,battery_c,ratings,n_ratings,sales_p,discount_p,sales_idx
0,Very Small,64,2,1,1,1800,4.5,38645,32999,0.17,127.52
1,Small,64,4,2,1,2815,4.5,244,57149,0.04,1.39
2,Very Small,64,2,1,1,1800,4.5,38645,32999,0.17,127.52
3,Medium,64,3,1,1,2942,4.6,5366,42999,0.10,23.07
4,Medium,128,4,2,1,2815,4.6,745,69149,0.02,5.15

In [13]:
means = df["sales_idx"].mean()
s = df["sales_idx"].std()

df_q1 = df[df["sales_idx"] > means + 2 * s].reset_index(drop = True)
df_q1.head()

,screen_size,ROM,RAM,n_rear_cam,n_front_cam,battery_c,ratings,n_ratings,sales_p,discount_p,sales_idx
0,Medium,128,6,2,1,4000,4.6,122001,18999,0.09,231.79
1,Large,128,6,4,2,4500,4.5,267028,15999,0.20,427.22
2,Large,32,2,2,1,5000,4.4,223672,7499,0.16,167.73
3,Large,32,2,2,1,5000,4.4,223672,7499,0.16,167.73
4,Medium,16,2,2,1,4000,4.4,226996,6499,0.07,147.52

In [16]:
df_q1["score"] = df_q1["ROM"] / 32 + df_q1["RAM"] / 2 + df_q1["n_rear_cam"] + df_q1["n_front_cam"] + df_q1["battery_c"] / 1000
df_q1["score"].mean() # 11.01

np.float64(11.01125)

In [17]:
# Q2

In [18]:
df_q2 = df.drop(columns = "screen_size")
df_q2.head()

,ROM,RAM,n_rear_cam,n_front_cam,battery_c,ratings,n_ratings,sales_p,discount_p,sales_idx
0,64,2,1,1,1800,4.5,38645,32999,0.17,127.52
1,64,4,2,1,2815,4.5,244,57149,0.04,1.39
2,64,2,1,1,1800,4.5,38645,32999,0.17,127.52
3,64,3,1,1,2942,4.6,5366,42999,0.10,23.07
4,128,4,2,1,2815,4.6,745,69149,0.02,5.15

In [20]:
from sklearn.preprocessing import StandardScaler

# StandardScaler는 각 컬럼을 평균 0, 표준편차 1로 맞춰줍니다.
scaler = StandardScaler().fit_transform(df_q2)

In [22]:
kmeans = KMeans(n_clusters=4, random_state=123).fit(df_scaled)

In [23]:
df_q2["cluster"] = kmeans.labels_
df_q2.head()

,ROM,RAM,n_rear_cam,n_front_cam,battery_c,ratings,n_ratings,sales_p,discount_p,sales_idx,cluster
0,64,2,1,1,1800,4.5,38645,32999,0.17,127.52,1
1,64,4,2,1,2815,4.5,244,57149,0.04,1.39,1
2,64,2,1,1,1800,4.5,38645,32999,0.17,127.52,1
3,64,3,1,1,2942,4.6,5366,42999,0.10,23.07,1
4,128,4,2,1,2815,4.6,745,69149,0.02,5.15,1

In [25]:
# Q3
# 단계1) 명목형 변수인 화면 크기(screen_size)를 One Hot Encoding을 실시하여 더미변수 생성 
# 단계2) Scikit Learn라이브러리의 train_test_split() 클래스로 학습 데이터와 평가 데이터 분할 
# 단계3) 단계2의 데이터를 Min-Max 정규화 실시
# 단계4) 단계3의 데이터를 사용하여 k값을 변화시키며 k-NN 분석을 실시하고 최적의 k 탐색 
# 단계5) 단계4에서 확보한 최적의 k 기반으로 산출한 모델을 “model_best”로 지칭