In [137]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score

In [138]:
import sklearn
np.__version__, pd.__version__, sklearn.__version__

('2.4.3', '3.0.1', '1.8.0')

### Q1.

In [139]:
df = pd.read_csv("set_02_data.csv")

In [140]:
ls_cols = ['OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 
           'TechSupport', 'StreamingTV', 'StreamingMovies']

In [141]:
len(df)

6465

In [142]:
# 시니어가 아닌 남성을 대상으로.

In [143]:
df_q1 = df.loc[(df["SeniorCitizen"] == 0) & (df["gender"] == "Male"), ls_cols]
len(df_q1)

2699

In [144]:
df_q1 = df_q1.loc[df_q1["OnlineSecurity"  ].isin(["Yes", "No"]), ]
df_q1 = df_q1.loc[df_q1["OnlineBackup"    ].isin(["Yes", "No"]), ]
df_q1 = df_q1.loc[df_q1["DeviceProtection"].isin(["Yes", "No"]), ]
df_q1 = df_q1.loc[df_q1["TechSupport"     ].isin(["Yes", "No"]), ]
df_q1 = df_q1.loc[df_q1["StreamingTV"     ].isin(["Yes", "No"]), ]
df_q1 = df_q1.loc[df_q1["StreamingMovies" ].isin(["Yes", "No"]), ]
df_q1.head(2)

,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies
1,No,No,Yes,Yes,Yes,Yes
6,No,Yes,No,Yes,Yes,No

In [145]:
df_q1 = df_q1.loc[df_q1[ls_cols[0]].isin(["Yes", "No"]), ]
df_q1 = df_q1.loc[df_q1[ls_cols[1]].isin(["Yes", "No"]), ]
df_q1 = df_q1.loc[df_q1[ls_cols[2]].isin(["Yes", "No"]), ]
df_q1 = df_q1.loc[df_q1[ls_cols[3]].isin(["Yes", "No"]), ]
df_q1 = df_q1.loc[df_q1[ls_cols[4]].isin(["Yes", "No"]), ]
df_q1 = df_q1.loc[df_q1[ls_cols[5]].isin(["Yes", "No"]), ]

In [146]:
for n in range(len(ls_cols)):
    df_q1 = df_q1.loc[df_q1[ls_cols[n]].isin(["Yes", "No"]), ]

for n_col in ls_cols:
    df_q1 = df_q1.loc[df_q1[n_col].isin(["Yes", "No"]), ]

In [147]:
df_q1["OnlineBackup"].unique()

<StringArray>
['No', 'Yes']
Length: 2, dtype: str

In [148]:
len(df_q1)

2232

In [149]:
ser_cnt = df_q1.apply(lambda x: (x == "Yes").sum(), axis = 1)
ser_cnt.head(3)

1     4
6     3
11    0
dtype: int64

In [150]:
df_q1["cnt"] = ser_cnt

In [151]:
df_q1.tail()

,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,cnt
6455,Yes,No,Yes,Yes,No,No,3
6458,Yes,No,No,Yes,Yes,No,3
6459,Yes,Yes,No,Yes,Yes,Yes,5
6461,Yes,No,Yes,Yes,No,No,3
6463,No,No,No,No,No,No,0

In [152]:
ser_cnt2 = ser_cnt.value_counts()
ser_cnt2.sort_index()

0    275
1    388
2    409
3    463
4    352
5    227
6    118
Name: count, dtype: int64

In [153]:
ser_cnt2[1] / ser_cnt2[6] # 3.28!!!

np.float64(3.288135593220339)

### Q2.

In [154]:
df = pd.read_csv("set_02_data.csv")

In [155]:
df_q2 = df[["tenure", "MonthlyCharges", "TotalCharges", "PaymentMethod"]].copy()
df_q2["dur"] = df_q2["TotalCharges"] // df_q2["MonthlyCharges"]
df_q2.head(2)

   tenure  MonthlyCharges  TotalCharges              PaymentMethod   dur
0      43           51.25        2151.6  Bank transfer (automatic)  41.0
1      31           79.30        2484.0               Mailed check  31.0

In [156]:
df_A = df_q2.loc[ df_q2["PaymentMethod"].str.contains("automatic"), ["tenure", "dur", "MonthlyCharges"]]
df_B = df_q2.loc[~df_q2["PaymentMethod"].str.contains("automatic"), ["tenure", "dur", "MonthlyCharges"]]
len(df_A), len(df_B)

(2805, 3660)

In [157]:
df_A.head(2)

   tenure   dur  MonthlyCharges
0      43  41.0           51.25
2      49  50.0           90.05

In [158]:
# df_A.corr().reset_index().melt(id_vars = "index")
stat_A = df_A.corr().replace(1, np.nan).max().max()
stat_B = df_B.corr().replace(1, np.nan).max().max()
stat_A, stat_B

(np.float64(0.9985017739420756), np.float64(0.9989839520673992))

In [159]:
round(abs(stat_A - stat_B), 4)

np.float64(0.0005)

### Q3.

In [160]:
df = pd.read_csv("set_02_data.csv")
df.head(2)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,6682-VCIXC,Female,0,Yes,Yes,43,No,No phone service,DSL,Yes,...,No,Yes,Yes,No,One year,Yes,Bank transfer (automatic),51.25,2151.6,No
1,2486-WYVVE,Male,0,Yes,No,31,Yes,Yes,DSL,No,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,79.30,2484.0,No

In [161]:
ls_col_x = ["SeniorCitizen", "Partner", "Dependents", "tenure", "MonthlyCharges", "TotalCharges", 
            "OnlineSecurity", "OnlineBackup", "DeviceProtection", "TechSupport", "StreamingMovies", "PaperlessBilling"]
df_q3 = df[["Churn"] + ls_col_x].copy()
df_q3.head(2)

,Churn,SeniorCitizen,Partner,Dependents,tenure,MonthlyCharges,TotalCharges,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingMovies,PaperlessBilling
0,No,0,Yes,Yes,43,51.25,2151.6,Yes,Yes,No,Yes,No,Yes
1,No,0,Yes,No,31,79.30,2484.0,No,No,Yes,Yes,Yes,Yes

In [162]:
# df_q3["Churn"] = df_q3["Churn"].replace({"Yes": 1, "No": 0})
# df_q3 = df_q3.replace({"Yes": 1, "No": 0})

In [163]:
# df_q3_obj = df_q3.loc[:, df_q3.dtypes == "object"] # 시험버전
df_q3_obj = df_q3.loc[:, df_q3.dtypes == "str"] # 최신버전
df_q3_obj.head(2)

,Churn,Partner,Dependents,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingMovies,PaperlessBilling
0,No,Yes,Yes,Yes,Yes,No,Yes,No,Yes
1,No,Yes,No,No,No,Yes,Yes,Yes,Yes

In [164]:
for n in range(df_q3_obj.shape[1]):
    print(df_q3_obj.iloc[:, n].unique())

<StringArray>
['No', 'Yes']
Length: 2, dtype: str
<StringArray>
['Yes', 'No']
Length: 2, dtype: str
<StringArray>
['Yes', 'No']
Length: 2, dtype: str
<StringArray>
['Yes', 'No', 'Pending', 'No internet service', 'Under despute']
Length: 5, dtype: str
<StringArray>
['Yes', 'No', 'Pending', 'No internet service', 'Under despute']
Length: 5, dtype: str
<StringArray>
['No', 'Yes', 'Pending', 'No internet service', 'Under despute']
Length: 5, dtype: str
<StringArray>
['Yes', 'No', 'Pending', 'No internet service', 'Under despute']
Length: 5, dtype: str
<StringArray>
['No', 'Yes', 'Pending', 'No internet service', 'Under despute']
Length: 5, dtype: str
<StringArray>
['Yes', 'No']
Length: 2, dtype: str

In [165]:
# df_q3_obj.apply(lambda x: [x.unique()]) # 시험버전
# df_q3_obj.apply(lambda x: x.unique()) # 최신버전
df_q3_obj.apply(lambda x: x.unique()).explode().unique() # 몰라도 됨.

<StringArray>
['No', 'Yes', 'Pending', 'No internet service', 'Under despute']
Length: 5, dtype: str

In [166]:
ser_repl = pd.Series([0, 1, -1, -1, -1], 
                     index = ['No', 'Yes', 'Pending', 'No internet service', 'Under despute'])
ser_repl.to_dict() # 몰라도 됨.

{'No': 0,
 'Yes': 1,
 'Pending': -1,
 'No internet service': -1,
 'Under despute': -1}

In [167]:
df_q3 = df_q3.replace(ser_repl)

In [168]:
df_q3.head(2)

,Churn,SeniorCitizen,Partner,Dependents,tenure,MonthlyCharges,TotalCharges,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingMovies,PaperlessBilling
0,0,0,1,1,43,51.25,2151.6,1,1,0,1,0,1
1,0,0,1,0,31,79.30,2484.0,0,0,1,1,1,1

In [169]:
df_q3.dtypes # 시험버전에서는 int64로 되지만, Pandas 3.0 이상의 최신버전에서는 "object"로 되어서 또 한번 변환해야 함.

Churn                object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
MonthlyCharges      float64
TotalCharges        float64
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingMovies      object
PaperlessBilling     object
dtype: object

In [170]:
# 최신버전만 작성하는 코드
ser_idx = df_q3.dtypes[df_q3.dtypes == "object"].index
for n in ser_idx:
    df_q3[n] = df_q3[n].astype("int")

In [171]:
df_q3.dtypes

Churn                 int64
SeniorCitizen         int64
Partner               int64
Dependents            int64
tenure                int64
MonthlyCharges      float64
TotalCharges        float64
OnlineSecurity        int64
OnlineBackup          int64
DeviceProtection      int64
TechSupport           int64
StreamingMovies       int64
PaperlessBilling      int64
dtype: object

In [172]:
df_q3.head(2)

,Churn,SeniorCitizen,Partner,Dependents,tenure,MonthlyCharges,TotalCharges,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingMovies,PaperlessBilling
0,0,0,1,1,43,51.25,2151.6,1,1,0,1,0,1
1,0,0,1,0,31,79.30,2484.0,0,0,1,1,1,1

In [173]:
# str.extract()
ser_id_num = df["customerID"].str.split("-", expand = True)[0].astype("int")
# ser_id_num % 4

In [174]:
df_train = df_q3.loc[ser_id_num % 4 != 0, ]
df_test  = df_q3.loc[ser_id_num % 4 == 0, ]
len(df_train), len(df_test)

(4832, 1633)

In [175]:
df_train.dtypes

Churn                 int64
SeniorCitizen         int64
Partner               int64
Dependents            int64
tenure                int64
MonthlyCharges      float64
TotalCharges        float64
OnlineSecurity        int64
OnlineBackup          int64
DeviceProtection      int64
TechSupport           int64
StreamingMovies       int64
PaperlessBilling      int64
dtype: object

In [176]:
df_train.head(2)

,Churn,SeniorCitizen,Partner,Dependents,tenure,MonthlyCharges,TotalCharges,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingMovies,PaperlessBilling
0,0,0,1,1,43,51.25,2151.6,1,1,0,1,0,1
1,0,0,1,0,31,79.30,2484.0,0,0,1,1,1,1

In [177]:
ls_col_num = ["SeniorCitizen", "tenure", "MonthlyCharges", "TotalCharges"]
df_train_num = df_train[ls_col_num]
df_train_obj = df_train.loc[:, ~df_train.columns.isin(ls_col_num)]
df_train_obj.head(1)

,Churn,Partner,Dependents,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingMovies,PaperlessBilling
0,0,1,1,1,1,0,1,0,1

In [178]:
df_test_num = df_test[ls_col_num]
df_test_obj = df_test.loc[:, ~df_test.columns.isin(ls_col_num)]
df_test_obj.head(1)

,Churn,Partner,Dependents,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingMovies,PaperlessBilling
4,0,0,0,0,0,0,0,0,1

In [179]:
model_nor = MinMaxScaler().fit(df_train_num)
arr_train_num_nor = model_nor.transform(df_train_num)
arr_test_num_nor  = model_nor.transform(df_test_num)

In [180]:
arr_train_num_nor[:2, ]

array([[0.        , 0.5915493 , 0.32835821, 0.24610254],
       [0.        , 0.42253521, 0.60746269, 0.28445978]])

In [181]:
# df_train2 = pd.concat([df_train_obj, arr_train_num], axis = 1)
df_train_num_nor = pd.DataFrame(arr_train_num_nor, columns = df_train_num.columns)
df_train2 = pd.concat([df_train_obj.reset_index(drop = True), # 🚨🚨🚨🚨
                       df_train_num_nor], axis = 1)
df_train2.tail()

,Churn,Partner,Dependents,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingMovies,PaperlessBilling,SeniorCitizen,tenure,MonthlyCharges,TotalCharges
4827,0,1,1,1,0,1,1,0,1,0.0,0.507042,0.443284,0.260775
4828,1,1,0,0,0,1,0,1,1,1.0,0.802817,0.800498,0.668563
4829,0,0,1,0,0,0,1,1,1,0.0,0.112676,0.508955,0.063761
4830,0,1,0,1,0,1,1,0,1,0.0,0.591549,0.656716,0.406230
4831,0,1,1,-1,-1,1,1,-1,0,0.0,0.873239,0.010945,0.143661

In [182]:
df_test_num_nor = pd.DataFrame(arr_test_num_nor, columns = df_test_num.columns)
df_test2 = pd.concat([df_test_obj.reset_index(drop = True), # 🚨🚨🚨🚨
                      df_test_num_nor], axis = 1)
df_test2.head(2)

,Churn,Partner,Dependents,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingMovies,PaperlessBilling,SeniorCitizen,tenure,MonthlyCharges,TotalCharges
0,0,0,0,0,0,0,0,0,1,0.0,0.0,0.521891,0.005977
1,1,0,0,-1,-1,-1,-1,-1,0,0.0,0.0,0.016418,0.000115

In [183]:
df_train3 = df_train2[df_train.columns]
df_train3.head(1)

,Churn,SeniorCitizen,Partner,Dependents,tenure,MonthlyCharges,TotalCharges,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingMovies,PaperlessBilling
0,0,0.0,1,1,0.591549,0.328358,0.246103,1,1,0,1,0,1

In [184]:
df_test3 = df_test2[df_test.columns]
df_test3.head(1)

,Churn,SeniorCitizen,Partner,Dependents,tenure,MonthlyCharges,TotalCharges,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingMovies,PaperlessBilling
0,0,0.0,0,0,0.0,0.521891,0.005977,0,0,0,0,0,1

In [189]:
model_lr = LogisticRegression(random_state = 123)
model_lr.fit(X = df_train3.drop(columns = "Churn"),
             y = df_train3["Churn"])
pred = model_lr.predict(df_test3.drop(columns = "Churn"))
pred[:4]

array([1, 0, 0, 1])

In [187]:
round(f1_score(y_true = df_test3["Churn"], y_pred = pred), 2)

0.58